% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{section}{-1}
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaklines,
  commandchars=\\\{\}

\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={QRM II Graded Assignment (15)},
  pdfauthor={Nynke Latham 2862763, RIk de Bruijn 2894496, Meike Bliek 2892575},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{QRM II Graded Assignment (15)}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Period 1, 2026}
\author{Nynke Latham 2862763, RIk de Bruijn 2894496, Meike Bliek
2892575}
\date{02-10-2026}

\begin{document}
\maketitle

\section{Introduction}\label{introduction}

This assignment is to be completed in groups of 4-5. Further, all
students in your group need to be assigned to the same R tutorial group
(Friday's tutorial). You can sign yourself up for a group on Canvas.
Please do so
\textbf{before the start of your first R tutorial on Friday September 4th.}
You can use the Discussion Board in Canvas if you do not have a group
yet or if your group is incomplete.

The assignment has 5 parts, and each part corresponds to the course
material of that week (with the exclusion of week 6, for which there is
no R programming material).

You are supposed to hand in these assignments on Canvas at the following
dates:

\begin{itemize}
\tightlist
\item
  \textbf{Deadline 1} \emph{Sunday September 27th, at 23:59pm}: you are
  supposed to hand in weeks 1, 2, and 3 of this assignment. This will
  determine 18\% of your overall course grade
\item
  \textbf{Deadline 2} \emph{Sunday October 11th, at 23:59pm}: you are
  supposed to hand in weeks 4, and 5 of this assignment. This will
  determine 12\% of your overall course grade
\end{itemize}

The R tutorials (each Friday) will consist of two halves. During the
first half, you will discuss the tutorial exercises. These can be
downloaded separately from Canvas. During the second half, you can work
on this graded assignment within your own group. The purpose is that you
find out how to work with R for doing statistical analyses by yourself.
The tutorial exercises are meant to teach you basic commands to get you
started, but to answer the problem sets in this assignment, you might
need to research your own solutions, and use functions and commands not
described in the tutorial exercises. Learning how to solve your own
research problems is integral part of learning R. When you and your
group get stuck on how to approach an exercise, the hierarchy in finding
your way is as follows:

\begin{itemize}
\tightlist
\item
  use the concepts from the tutorial exercises;
\item
  use the cheat sheets available on Canvas;
\item
  use Google, YouTube, StackOverflow, or another website;
\item
  ask the teacher.
\end{itemize}

The use of generative AI is \textbf{not} permitted and may result in a
grade of 0. See the AI protocol in the course manual for details.

To answer the assignment, you can simply fill out this R markdown
document. There are designated places which you can fill with R code.
There are also designated spaces for you to answer each question. Often,
the structure of an answer will be as follows. First, you type the R
code in the designated box. This will show how you analyzed the data to
get the answer to the question. Below the box for the R code, you will
then summarize your answer to the question, i.e.~what are the
conclusions that you draw from the data analysis?

When handing in, you are supposed to submit this .Rmd file, and a
knitted version of this document. You can knit this document to pdf,
word, or html. Knitting to pdf requires you to have a .tex distribution
installed on your computer. Knitting to Word requires you to have Word
installed.

The exercises are designed such that you should be able to finish the
majority of them during the tutorial each week. If you are not able to
finish them fully during that time, you are expected to work on it in
your own time using the computers on campus or your own device. It is
best to meet as a group in-person when working together. If you want to
work remotely, github is a good platform to guarantee smooth
collaboration. Alternatively, you can email this .Rmd file back and
forth to one another as a group, but this is not recommended as it is
more cumbersome.

We encourage you to keep your code blocks, printing statements, and
final answers, as short as possible. In any case, there is a page limit
of 6 pages per week, which encompasses the total length of this document
which consists of the questions, your coding lines, and your answers.
When your answers to questions of the respective week exceed this page
limit, they will not be graded, resulting in zero points.

\section{Week 1}\label{week-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the dataset ``movies1.tsv'' on Canvas. Describe your data set:
  How many observations does it have. How many variables are there? How
  many subjects? What consists of a subject? \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE code }

\FunctionTok{nrow}\NormalTok{(movies\_one)              }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 505
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#observations }
\FunctionTok{ncol}\NormalTok{(movies\_one)              }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# variables}
\FunctionTok{n\_distinct}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{title)  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 505
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#unique movies (subjects)}
\FunctionTok{glimpse}\NormalTok{(movies\_one)           }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 505
## Columns: 19
## $ index               <dbl> 1773, 2540, 1174, 3262, 4324, 214, 1737, 610, 2738~
## $ budget              <dbl> 2.70e+07, 1.50e+07, 4.00e+07, 0.00e+00, 0.00e+00, ~
## $ keywords            <chr> "fbi island serial killer series of murders", "fir~
## $ original_language   <chr> "en", "en", "en", "en", "en", "en", "en", "en", "e~
## $ title               <chr> "Mindhunters", "Krampus", "Ride Along 2", "Enough ~
## $ popularity          <dbl> 17.193659, 31.565117, 25.136082, 14.969093, 0.1478~
## $ release_date        <date> 2004-05-07, 2015-11-26, 2016-01-14, 2013-09-18, 2~
## $ revenue             <dbl> 21148829, 61548707, 124827316, 25288872, 0, 325756~
## $ runtime             <dbl> 106, 98, 102, 93, 97, 130, 108, 99, 100, 99, 82, 1~
## $ vote_average        <dbl> 6.3, 5.9, 6.1, 6.6, 6.0, 6.2, 5.5, 4.4, 6.0, 6.2, ~
## $ vote_count          <dbl> 333, 584, 555, 348, 9, 597, 640, 533, 210, 371, 11~
## $ genre               <chr> "Thriller", "Comedy", "Comedy", "Drama", "Drama", ~
## $ release_year        <dbl> 2004, 2015, 2016, 2013, 2006, 2000, 2016, 2014, 20~
## $ release_month       <dbl> 5, 11, 1, 9, 10, 3, 2, 1, 2, 9, 9, 12, 12, 11, 5, ~
## $ release_day         <dbl> 7, 26, 14, 18, 27, 15, 4, 10, 14, 29, 22, 19, 13, ~
## $ first_actor         <chr> "LL Cool", "Adam Scott", "Kevin Hart", "Julia Loui~
## $ first_actor_gender  <chr> NA, "male", "male", "female", "male", "male", "fem~
## $ director_first_name <chr> "Renny", "Michael", "Tim", "Nicole", "Regardt", "W~
## $ director_gender     <chr> "male", "male", "male", "female", NA, "male", "mal~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#all variables}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

The dataset contains 505 observations and 19 variables. There are 505
subjects, because every row is a movie and each movie title appears once
so the number of subjects equals the number of observations. A subject
is a single movie described by variables such as its title, budget,
revenue, genre, runtime, release date, ratings and the first actor and
director.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Which of the following types of variables are present in your data
  set? (i) nominal; (ii) ordinal; (iii); continuous; (iv) discrete. If
  present, name one example of such a variable present in your data set.
  \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{glimpse}\NormalTok{(movies\_one)                 }\CommentTok{\# overview of variable types}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 505
## Columns: 19
## $ index               <dbl> 1773, 2540, 1174, 3262, 4324, 214, 1737, 610, 2738~
## $ budget              <dbl> 2.70e+07, 1.50e+07, 4.00e+07, 0.00e+00, 0.00e+00, ~
## $ keywords            <chr> "fbi island serial killer series of murders", "fir~
## $ original_language   <chr> "en", "en", "en", "en", "en", "en", "en", "en", "e~
## $ title               <chr> "Mindhunters", "Krampus", "Ride Along 2", "Enough ~
## $ popularity          <dbl> 17.193659, 31.565117, 25.136082, 14.969093, 0.1478~
## $ release_date        <date> 2004-05-07, 2015-11-26, 2016-01-14, 2013-09-18, 2~
## $ revenue             <dbl> 21148829, 61548707, 124827316, 25288872, 0, 325756~
## $ runtime             <dbl> 106, 98, 102, 93, 97, 130, 108, 99, 100, 99, 82, 1~
## $ vote_average        <dbl> 6.3, 5.9, 6.1, 6.6, 6.0, 6.2, 5.5, 4.4, 6.0, 6.2, ~
## $ vote_count          <dbl> 333, 584, 555, 348, 9, 597, 640, 533, 210, 371, 11~
## $ genre               <chr> "Thriller", "Comedy", "Comedy", "Drama", "Drama", ~
## $ release_year        <dbl> 2004, 2015, 2016, 2013, 2006, 2000, 2016, 2014, 20~
## $ release_month       <dbl> 5, 11, 1, 9, 10, 3, 2, 1, 2, 9, 9, 12, 12, 11, 5, ~
## $ release_day         <dbl> 7, 26, 14, 18, 27, 15, 4, 10, 14, 29, 22, 19, 13, ~
## $ first_actor         <chr> "LL Cool", "Adam Scott", "Kevin Hart", "Julia Loui~
## $ first_actor_gender  <chr> NA, "male", "male", "female", "male", "male", "fem~
## $ director_first_name <chr> "Renny", "Michael", "Tim", "Nicole", "Regardt", "W~
## $ director_gender     <chr> "male", "male", "male", "female", NA, "male", "mal~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{genre)            }\CommentTok{\# nominal: categories without order}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Thriller"    "Comedy"      "Drama"       "Action"      "Documentary"
##  [6] "Family"      NA            "Adventure"   "Fantasy"     "Fiction"    
## [11] "Horror"      "Crime"       "Romance"     "Music"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{popularity)      }\CommentTok{\# continuous: decimal values}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 2.386e-03 4.759e+00 1.414e+01 2.283e+01 2.985e+01 2.037e+02
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{vote\_count)      }\CommentTok{\# discrete: whole numbers (counts)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0    47.0   255.0   802.9   914.0 11800.0
\end{verbatim}

\textbf{Your Answer:} (i) Nominal: A nominal variable has categories
without an order. Example genre: Thriller, Comedy, Drama, Action. Other
examples are original\_language and director\_gender. (ii) Ordinal: An
ordinal variable has categories with a meaningful order, but no known
distance between them like low, medium, high. None of the variables in
this data set is a ordered category. (iii) Continuous: Present. A
continuous variable can take any value within a range including
decimals. Example: popularity. Other examples are revenue, budget and
run time. (iv) Discrete: A discrete variable can only take separate,
countable values. Example: vote\_count, the number of votes a movie
received. release\_month (1--12) and release\_year are other examples.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  A movie studio wants to know which types of movies give maximal
  revenue. Perform the following steps to provide the movie studio with
  an analysis which corresponds to their request:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Summarize the variable revenue and report its mean, median, maximum,
  and minimum. \textbf{[2 points]}
\item
  Which movie has the highest revenue in your data set and how much is
  this revenue. Which movie has the lowest and how much is its revenue?
  If multiple movies have the exact same highest or lowest revenue, give
  only one example. \textbf{[2 points]}
\item
  Create a histogram of the variable revenue. Make sure it has an
  appropriate title, and appropriate titles and labels for the x- and
  y-axis. Describe the shape of the histogram. What does this tell you
  about the nature of making money in the movies industry?
  \textbf{[2 points]}
\item
  Add a new variable to your data set: the log of revenue. When creating
  this variable, what happens to movies for which revenue is zero? What
  then happens when you calculate the mean of log revenue?
  \textbf{[2 points]}
\item
  For movies that have a revenue of zero, replace log of revenue with
  ``NA''. What is now the mean of log of revenue? Create a histogram for
  log revenue, again with an appropriate title, x- and y-axis labels.
  Describe the shape of this histogram. \textbf{[2 points]}
\item
  For the variables revenue and log of revenue calculate their skewness
  and kurtosis. How do these numbers relate to the shape of the
  histograms that you estimated under d.) and e.)? \textbf{[2 points]}
\end{enumerate}

For each step, you should provide first all the code you used to answer
the question and then formulate an answer using full sentences.

Each week consists of 1, 2, or 3 subquestions. The total amount of
points you can earn per week is 20 points.

\emph{Step a}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 0.000e+00 0.000e+00 1.948e+07 9.482e+07 1.043e+08 2.788e+09
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 94815482
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{median}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19480739
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{max}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2787965087
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{min}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\textbf{Your Answer:} The mean revenue is about 94.8 million dollar
(94.815.482). The median is about \$19.5 million dollar (19.480.739).
The maximum is 2.787.965.087 dollar and the minimum is 0 dollar. The
mean is five times higher than the median which shows that a small
number of successful movies increase average.

\emph{Step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}

\NormalTok{movies\_one[}\FunctionTok{which.max}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue), }
           \FunctionTok{c}\NormalTok{(}\StringTok{"title"}\NormalTok{, }\StringTok{"revenue"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   title     revenue
##   <chr>       <dbl>
## 1 Avatar 2787965087
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies\_one[}\FunctionTok{which.min}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue), }
           \FunctionTok{c}\NormalTok{(}\StringTok{"title"}\NormalTok{, }\StringTok{"revenue"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   title               revenue
##   <chr>                 <dbl>
## 1 Faith Like Potatoes       0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 160
\end{verbatim}

\textbf{Your Answer:} The movie with the highest revenue is Avatar, with
a revenue of 2,787,965,087 dollar. The lowest revenue is 0 dollar, which
is shared by 160 movies; one example is Faith Like Potatoes.

\emph{Step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{ggplot}\NormalTok{(movies\_one, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ revenue)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{30}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\FunctionTok{label\_number}\NormalTok{(}\AttributeTok{scale =} \FloatTok{1e{-}6}\NormalTok{, }\AttributeTok{suffix =} \StringTok{"M"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Histogram of movie revenue"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Revenue (in millions of dollars)"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Number of movies"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-5-1.pdf}}

\textbf{Your Answer:} The Histogram show that a lot of movies don't make
a lot of money. It is very right sided. Ninety percent of the movies
earn less than 244 million dollars while the highest revenue is almost
2.8 billion dollars. This shows that making money in the movie industry
is very concentrated with a few movies. Most movies earn little or
nothing while a few blockbusters earn extremely high revenues.

\emph{Step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{log}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}

\FunctionTok{sum}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{==} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 160
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -Inf
\end{verbatim}

\textbf{Your Answer:}

For movies with a revenue of zero, the log is undefined. Rstudio returns
-Inf (minus infinity), since log(0) = -∞. This affects 160 movies.
Because of this the mean of log revenue is -Inf and is therefore not
useful.

\emph{Step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue))}

\FunctionTok{mean}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17.4498
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(movies\_one, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ log\_revenue)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Histogram of log revenue"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Log of revenue"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Number of movies"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-7-1.pdf}}

\textbf{Your Answer:} When replacing the log of zero revenue with N.A.
the mean of log revenue is about 17.45 using the left over 345 movies.
The histogram is uni modal and left-skewed. Most values lie between
roughly 16 and 21, with a peak around 18, and there is a thin tail to
the left formed by a few movies with a very low positive revenue. The
shape is much more symmetric than the histogram of the raw revenue.

\emph{Step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}

\FunctionTok{skewness}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.049774
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kurtosis}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 63.28088
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skewness}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -2.290049
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kurtosis}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 12.5771
\end{verbatim}

\textbf{Your Answer:}

For revenue the skewness is about 6,05 and the kurtosis is about 63,3.
For log revenue the skewness is about -2,29 and the kurtosis is about
12,6. A skewness of 6,05 confirms the strong right skew that we see in
the histogram of revenue, and a kurtosis far above 3 the value for a
normal distribution means heavy tails so extreme outliers such as
Avatar. For log revenue the skewness is negative in line with the thin
left tail in the histogram and both numbers are much closer to those of
a normal distribution. The kurtosis of 12,6 is still above 3, so the log
transformation makes the distribution more symmetric but does not make
it fully normal.

\section{Week 2}\label{week-2}

1 Is your dataset movies1.tsv the full population, or is it a sample of
a larger population? If the latter, how would you describe the full
population? \textbf{[4 points]}

\emph{Your answer here:}

The dataset movies1.tsv (movie\_one) is a sample not the full
population. It contains only 505 movies, while there are thousands of
movies released yearly, so this is clearly a smaller part rather than
every movie that exists.

2 For this question, you will assume that your data set is the full
population.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  What is the mean of the variable vote\_average in your data set?
  \textbf{[2 points]}
\item
  Create a new data set, called movies\_sample. Make sure that it is a
  random sample of your data set of 25 movies. What is the mean of
  vote\_average in this random sample? How does it compare to the mean
  of vote\_average in 2a? \textbf{[2 points]}
\item
  In a for loop, create 100 different samples of 25 movies, as in b, and
  estimate the mean within each sample. Save the mean of each sample in
  a vector called sample\_means. So the first position of the vector
  would have the mean of the first sample, the second position the mean
  of the second sample, etc. Print the start of this vector.
  \textbf{[2 points]}
\item
  Summarize and make a histogram of sample\_means. What is the mean,
  standard deviation and shape of its distribution? \textbf{[2 points]}
\item
  Using the formulas of the \emph{Central Limit Theorem}, give the
  distribution of the sample mean of vote\_average in a sample of 25
  movies from your population (including its expected value and standard
  deviation). How do these values compare to your answers at d.)?
  \textbf{[2 points]}
\end{enumerate}

\emph{Step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{mean}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{vote\_average)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.042772
\end{verbatim}

\textbf{Your Answer:}

The mean of vote\_average in the full population (505 movies) is
6.042772 \emph{Step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{movies\_sample }\OtherTok{\textless{}{-}}\NormalTok{ movies\_one[}\FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(movies\_one), }\DecValTok{25}\NormalTok{), ]}

\FunctionTok{mean}\NormalTok{(movies\_sample}\SpecialCharTok{$}\NormalTok{vote\_average)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.904
\end{verbatim}

\textbf{Your Answer:}

The mean of vote\_average in this random sample of 25 movies is close
(5.904) but not exactly equal to the population mean of 6.04 from the
question before. Because the sample only contains 25 out of 505 its mean
is affected by sampling variation: a different random sample would give
a slightly different mean. Still, since the sample was drawn randomly it
should on average be a reasonable estimate of the population mean

\emph{Step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{sample\_means }\OtherTok{\textless{}{-}} \FunctionTok{numeric}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{100}\NormalTok{) \{}
\NormalTok{  sample\_i }\OtherTok{\textless{}{-}}\NormalTok{ movies\_one[}\FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(movies\_one), }\DecValTok{25}\NormalTok{), ]}
\NormalTok{  sample\_means[i] }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(sample\_i}\SpecialCharTok{$}\NormalTok{vote\_average)}
\NormalTok{\}}
\FunctionTok{head}\NormalTok{(sample\_means)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.904 5.528 6.096 6.020 6.168 5.824
\end{verbatim}

\textbf{Your Answer:}

The vector sample\_means contains the mean vote\_average of 100
different random samples of 25 movies. The first values of the vector
are printed above with head().

\emph{Step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}

\FunctionTok{summary}\NormalTok{(sample\_means)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   5.324   5.916   6.096   6.037   6.196   6.448
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(sample\_means)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2337529
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{data.frame}\NormalTok{(sample\_means), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sample\_means)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Histogram of sample means of vote\_average (100 samples of n = 25)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Sample mean of vote\_average"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Number of samples"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-12-1.pdf}}

\textbf{Your Answer:}

The mean of sample\_means is approximately 6.037 and is very close to
the population mean of 6.04. The standard deviation of sample\_means is
approximately 0.2337529. The histogram is bell-shaped centered around a
sample mean of roughly 6.037, with a slight left skew. This shape is
close to what the Central Limit Theorem predicts: even though only 100
samples were drawn, the distribution of sample means already resembles a
normal distribution.

\emph{Step e}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop\_mean }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{vote\_average)}
\NormalTok{pop\_sd }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{vote\_average)}

\NormalTok{pop\_mean                     }\CommentTok{\# expected value of the sample mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.042772
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop\_sd }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{25}\NormalTok{)            }\CommentTok{\# standard deviation (standard error) of the sample mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2383468
\end{verbatim}

\textbf{Your Answer:}

According to the Central Limit Theorem, for a large enough sample size
the distribution of the sample mean is approximately normal, \ldots with
expected value equal to the population mean, \(\mu = 6.043\), and
standard deviation (standard error) equal to
\(\sigma / \sqrt{n} = 1.192 / \sqrt{25} \approx 0.238\). This is very
close to what we found by simulation in d.: a mean of 6.096and a
standard deviation of 0.2337529. The small differences are due to
sampling variation, since we only drew 100 samples rather than an
infinite number of samples. This confirms the Central Limit Theorem:
even though the original variable \texttt{vote\_average} is not
perfectly normally distributed, the distribution of its sample mean is
approximately normal and centered on the population mean, with a spread
that shrinks as the sample size n increases.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Is there a variable in your data set which you would expect to follow
  a discrete uniform distribution? Explain, without looking at the data,
  why you expect this data to be discrete uniform. If the data would
  indeed follow a discrete uniform distribution, what would you expect
  the mean and standard deviation of this variable to be? Next, plot a
  histogram of the variable, and plot an appropriate discrete uniform
  distribution on top of this histogram. Comment whether the variable
  indeed follows this expected distribution. If the distribution
  deviates from the discrete uniform distribution, explain why this is
  the case. \textbf{[6 points]}
\end{enumerate}

\textbf{Your Answer:}

we expect release\_month (the month in which a movie is released, 1--12)
to follow a discrete uniform distribution. Without looking at the data,
there is no a priori reason why movies would be more likely to release
in one particular month than another: a movie can in principle be
released in any of the 12 months, and each month is equally likely if
release timing were purely random. For a discrete uniform distribution
on the integers 1 to 12, the expected mean is
\(E(X) = \frac{1+n}{2} = \frac{1+12}{2} = 6.5\), and the expected
standard deviation is
\(SD(X) = \sqrt{\frac{n^2-1}{12}} = \sqrt{\frac{144-1}{12}} \approx 3.45\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\CommentTok{\# Theoretical values for a discrete uniform distribution on \{1, 2, ..., 12\}}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{12}
\NormalTok{theoretical\_mean }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+}\NormalTok{ n) }\SpecialCharTok{/} \DecValTok{2}
\NormalTok{theoretical\_sd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((n}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/} \DecValTok{12}\NormalTok{)}

\NormalTok{theoretical\_mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{theoretical\_sd}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.452053
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Actual mean and sd in the data}
\FunctionTok{mean}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{release\_month)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.968317
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{release\_month)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.462811
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Histogram with the discrete uniform distribution overlaid}
\FunctionTok{ggplot}\NormalTok{(movies\_one, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ release\_month)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(count)), }\AttributeTok{binwidth =} \DecValTok{1}\NormalTok{, }\AttributeTok{boundary =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \FunctionTok{nrow}\NormalTok{(movies\_one) }\SpecialCharTok{/}\NormalTok{ n, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{breaks =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{12}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Histogram of release month vs. discrete uniform distribution"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Release month"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Number of movies"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-13-1.pdf}}

\textbf{Your Answer:}

I expect \texttt{release\_month} (1--12) to follow a discrete uniform
distribution, since there is no a priori reason a movie would be more
likely to release in one month than another. For a discrete uniform
distribution on \{1, \ldots, 12\}, the expected mean is
\(\frac{1+12}{2} = 6.5\) and the expected standard deviation is
\(\sqrt{\frac{12^2-1}{12}} \approx 3.45\). The observed mean (6.97) and
standard deviation (3.46) are close to these theoretical values, but the
histogram shows the distribution is not truly uniform: there is a clear
peak around September--October and relatively low counts in February and
April. This deviates from the flat pattern expected under a discrete
uniform distribution. This makes sense because release timing is not
random: studios strategically schedule releases around the autumn
festival season, while months like February and April are typically
considered weaker box-office periods and are avoided for major releases.

\section{Week 3}\label{week-3}

For the next part of the assignment, assume that the movies in your data
frame are a random sample of a larger population of movies.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Give a 90 percent confidence interval for the variable \emph{revenue}.
  Interpret the result. \textbf{[2 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}


\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\NormalTok{mean\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\NormalTok{sd\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue)}
\NormalTok{se\_revenue }\OtherTok{\textless{}{-}}\NormalTok{ sd\_revenue }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}

\NormalTok{t\_crit }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}

\NormalTok{lower }\OtherTok{\textless{}{-}}\NormalTok{ mean\_revenue }\SpecialCharTok{{-}}\NormalTok{ t\_crit }\SpecialCharTok{*}\NormalTok{ se\_revenue}
\NormalTok{upper }\OtherTok{\textless{}{-}}\NormalTok{ mean\_revenue }\SpecialCharTok{+}\NormalTok{ t\_crit }\SpecialCharTok{*}\NormalTok{ se\_revenue}

\NormalTok{lower}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 79639410
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upper}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 109991553
\end{verbatim}

\textbf{Your Answer:}

The 90\% confidence interval for the mean revenue is approximately
{[}79,639,410 ; 109,991,553{]}. This means that if we were to repeat
this sampling many times and construct a 90\% confidence interval each
time, about 90\% of those intervals would contain the real population
mean of the revenue. We are 90\% confident that the true mean revenue of
the full population of movies lies between roughly 79.6 and 110.0
million dollar.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  How many movies in your sample were directed by a male director? How
  many by a female director? \textbf{[2 points]}
\item
  Test the null hypothesis that the chance that a movie is being
  directed by a male or female director is equal. Clearly state your
  null hypothesis and alternative hypothesis, and your chosen
  significance level. Use an appropriate R function to test your
  hypothesis, and state your conclusion. Also give the p-value that
  corresponds to your test statistic. \textbf{[2 points]}
\item
  Recode revenue such that it is measured in millions of dollars. What
  is the variance of revenue for movies with a male director? What is
  the variance of revenue for movies with a female director?
  \textbf{[2 points]}
\item
  Assume that the variance of revenue for movies with a male director in
  your data is the same as the variance for movies with a male director
  in your population (that is, there is no sampling uncertainty in this
  estimate). Now, set up a hypothesis test to test for the null
  hypothesis that the variance of revenue for movies with a female
  director is equal to the variance for movies with a male director.
  Clearly state your null hypothesis and alternative hypothesis, and
  your chosen significance level. Calculate your test statistic and tell
  how your test statistic is distributed, and state your conclusion.
  Also give the p-value that corresponds to your test statistic.
  \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}

\FunctionTok{table}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## female   male 
##     44    426
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"male"}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 426
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"female"}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 44
\end{verbatim}

\textbf{Your Answer:}

In the sample, 426 movies were directed by a male director and 44 movies
by a female director. There are also 35 movies with a missing (NA) value
for director\_gender

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}

\FunctionTok{binom.test}\NormalTok{(}\AttributeTok{x =} \DecValTok{426}\NormalTok{, }\AttributeTok{n =} \DecValTok{426} \SpecialCharTok{+} \DecValTok{44}\NormalTok{, }\AttributeTok{p =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Exact binomial test
## 
## data:  426 and 426 + 44
## number of successes = 426, number of trials = 470, p-value < 2.2e-16
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.8763630 0.9311527
## sample estimates:
## probability of success 
##               0.906383
\end{verbatim}

\textbf{Your Answer:}

Null hypothesis H0: the probability that a movie is directed by a male
director is P = 0.5 (male and female directors are equally likely).
\textbf{Alternative hypothesis \(H_1\):} \(p \neq 0.5\). Significance
level:** \(\alpha = 0.05\). Of the 470 movies with a known director
gender, 426 were directed by a man. A two-sided binomial test against
\(p = 0.5\) gives a test statistic based on 426 successes out of 470
trials, with a p-value that is essentially 0 (far below 0.001). Because
the p-value is much smaller than \(\alpha = 0.05\), we reject the null
hypothesis. There is very strong evidence that male and female directors
are not equally likely in this population; movies are directed by men
far more often than by women.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}

\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{revenue\_millions }\OtherTok{\textless{}{-}}\NormalTok{ movies\_one}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{/} \FloatTok{1e6}

\FunctionTok{var}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue\_millions[movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"male"}\NormalTok{], }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 48054.81
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue\_millions[movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"female"}\NormalTok{], }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17490.31
\end{verbatim}

\textbf{Your Answer:}

After recording revenue into millions of dollars, the variance of
revenue for movies with a male director is approximately 48,055 (million
squared), and for movies with a female director it is approximately
17,490 (million squared).

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}

\NormalTok{sigma\_sq\_male }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue\_millions[movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"male"}\NormalTok{], }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)  }\CommentTok{\# treated as known population variance}
\NormalTok{s\_sq\_female }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue\_millions[movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"female"}\NormalTok{], }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{n\_female }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"female"}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{chi\_sq\_stat }\OtherTok{\textless{}{-}}\NormalTok{ (n\_female }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ s\_sq\_female }\SpecialCharTok{/}\NormalTok{ sigma\_sq\_male}
\NormalTok{chi\_sq\_stat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.65053
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ n\_female }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 43
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*} \FunctionTok{min}\NormalTok{(}\FunctionTok{pchisq}\NormalTok{(chi\_sq\_stat, df), }\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pchisq}\NormalTok{(chi\_sq\_stat, df))}
\NormalTok{p\_value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.252287e-05
\end{verbatim}

\textbf{Your Answer:}

H0: \(\sigma^2_{female} = \sigma^2_{male}\) (approximately 48,055,
treated as a known population value). \textbf{\(H_1\):}
\(\sigma^2_{female} \neq \sigma^2_{male}\). \(\alpha = 0.05\). Since
\(\sigma^2_{male}\) is known, we test \(s^2_{female}\) against it using
\(\chi^2 = \frac{(n-1)s^2_{female}}{\sigma^2_{male}}\), which follows a
chi-square distribution with \(n-1 = 43\) degrees of freedom under
\(H_0\). The test statistic is \(\chi^2 \approx 15.65\), giving a
two-sided p-value of approximately 0.00008. Since this is well below
\(\alpha = 0.05\), wereject H0: the variance of revenue for
female-directed movies differs from (and is lower than) that for
male-directed movies.

3

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a scatter plot with year on the x axis and mean of revenue
  within that year on the y-axis. Make sure it has an appropriate title,
  and appropriate titles and labels for the x- and y-axis. Is revenue of
  movies increasing or decreasing over time? \textbf{[3 points]}
\item
  Recreate the scatter plot with year on the x axis and mean\_revenue on
  the y-axis, but now add bars around each point, indicating the 95\%
  confidence interval. \textbf{[3 points]}
\item
  If you look closely at the resulting plot in b.), you will probably
  see that the confidence intervals in some years are wider than in
  other years. What are some possible reasons that a confidence interval
  in a given year can be wide? Can you verify this using your data?
  \textbf{[4 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{yearly\_revenue }\OtherTok{\textless{}{-}}\NormalTok{ movies\_one }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(release\_year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{mean\_revenue =} \FunctionTok{mean}\NormalTok{(revenue))}

\FunctionTok{ggplot}\NormalTok{(yearly\_revenue, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ release\_year, }\AttributeTok{y =}\NormalTok{ mean\_revenue)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Mean movie revenue by release year"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Release year"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Mean revenue (dollars)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-19-1.pdf}}

\textbf{Your Answer:}

The scatter plot does not show a clear upward or downward trend in mean
revenue over time. There is a lot of variation each year with some years
showing very high average revenue and others much lower but no strong
overall pattern. \emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{yearly\_revenue }\OtherTok{\textless{}{-}}\NormalTok{ movies\_one }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(release\_year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{mean\_revenue =} \FunctionTok{mean}\NormalTok{(revenue),}
            \AttributeTok{sd\_revenue =} \FunctionTok{sd}\NormalTok{(revenue),}
            \AttributeTok{n =} \FunctionTok{n}\NormalTok{(),}
            \AttributeTok{se =}\NormalTok{ sd\_revenue }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n),}
            \AttributeTok{t\_crit =} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{),}
            \AttributeTok{ci\_lower =}\NormalTok{ mean\_revenue }\SpecialCharTok{{-}}\NormalTok{ t\_crit }\SpecialCharTok{*}\NormalTok{ se,}
            \AttributeTok{ci\_upper =}\NormalTok{ mean\_revenue }\SpecialCharTok{+}\NormalTok{ t\_crit }\SpecialCharTok{*}\NormalTok{ se)}

\FunctionTok{ggplot}\NormalTok{(yearly\_revenue, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ release\_year, }\AttributeTok{y =}\NormalTok{ mean\_revenue)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_errorbar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{ymin =}\NormalTok{ ci\_lower, }\AttributeTok{ymax =}\NormalTok{ ci\_upper)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Mean movie revenue by release year, with 95\% confidence intervals"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Release year"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Mean revenue (dollars)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-20-1.pdf}}

\textbf{Your Answer:}

The plot now shows the mean revenue per year together with a 95\%
confidence interval around each point, illustrating how precisely the
mean is estimated for each year.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{yearly\_revenue }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(ci\_upper }\SpecialCharTok{{-}}\NormalTok{ ci\_lower)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(release\_year, n, sd\_revenue, ci\_lower, ci\_upper)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 27 x 5
##    release_year     n sd_revenue    ci_lower   ci_upper
##           <dbl> <int>      <dbl>       <dbl>      <dbl>
##  1         1991     3 267045531. -451150178. 875605571.
##  2         1992     3 129834690. -112623364. 532431134.
##  3         1994     7 292685338. -139072255. 402305326.
##  4         2009    37 502939570.   57838647. 393215449.
##  5         2016    19 338706404.   35872184. 362374706.
##  6         1995     9 116438509.  -13443845. 165561277.
##  7         2012    36 256066373.   44614323. 217895114.
##  8         1998    15 135533982.    7875376. 157987811.
##  9         2011    22 157312285.   57549114. 197045834.
## 10         2000    19 141945943.   20026655. 156858164.
## # i 17 more rows
\end{verbatim}

\textbf{Your Answer:}

A confidence interval for a given year can be wide for two main reasons:
(1) a small sample size in that year, since the standard error is
\(s/\sqrt{n}\) and shrinks as n grows, and (2) a large standard
deviation of revenue within that year, meaning revenue values are very
spread out (e.g.~a mix of blockbusters and low-revenue movies). This can
indeed be verified in the data. For example, 1991 and 1992 have only 3
movies each, and their confidence intervals are among the widest in the
plot, showing that a small sample size drives up the width. Similarly,
2009 has a much larger sample (37 movies) but still has one of the
widest intervals, because its standard deviation of revenue is very high
(movies that year ranged from low-revenue films to a very high-grossing
blockbuster). In contrast, years like 1993 have both a small n and a low
standard deviation, resulting in a narrow interval. So both a small
sample size and high within-year variability contribute to wider
confidence intervals, and the data confirms that both factors are
present in different years.

\section{Week 4}\label{week-4}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  There is an argument going on in the movie studio. \emph{Bob} claims
  that production budgets are getting out of hand, and that the studio
  should focus on making cheaper movies. \emph{Chantal} disagrees. She
  tells Bob that ``Every dollar we spend on movie production is more
  than offset by the increase in movie revenue'\,'.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Set up a regression model to test Chantal's claim, and estimate it.
  That is, estimate:
  \[\text{Revenue}_i=\beta_0+\beta_1 \text{Budget}_i +\varepsilon_i.\]
  Print a summary of your estimated model. \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Test for the null hypothesis that \(\beta_1 \leq 1\). Report the
  p-value and state your conclusion. \textbf{[2 points]}
\item
  Next, estimate the model
  \[\text{Log Revenue}_i=\beta_0+\beta_1 \text{Log Budget}_i +\varepsilon_i.\]
  When creating the variables Log Revenue and Log Budget, make sure that
  movies with a Revenue or Budget of zero are assigned the value ``NA''.
  Print a summary of your estimated model. \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Which model has better fit? The level-level model or the log-log
  model? Explain. \textbf{[2 points]}
\item
  Who do you think is correct? Bob or Chantal? What would you advise the
  movie studio to do? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{model\_level }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ budget, }\AttributeTok{data =}\NormalTok{ movies\_one)}
\FunctionTok{summary}\NormalTok{(model\_level)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = revenue ~ budget, data = movies_one)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -420678243  -37658344   14833690   17600279 1964947903 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -1.760e+07  7.165e+06  -2.456   0.0144 *  
## budget       3.547e+00  1.302e-01  27.248   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 131700000 on 503 degrees of freedom
## Multiple R-squared:  0.5961, Adjusted R-squared:  0.5953 
## F-statistic: 742.5 on 1 and 503 DF,  p-value: < 2.2e-16
\end{verbatim}

The estimated level-level regression model is
\(\widehat{\text{Revenue}}_i = -17{,}600{,}000 + 3.547 \times \text{Budget}_i\).

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{coef}\NormalTok{(model\_level)[}\StringTok{"budget"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   budget 
## 3.546909
\end{verbatim}

The estimated slope coefficient is \(\beta_1\) is approximately 3.547:
on average, each extra dollar of production budget is associated with
about \$3.55 more revenue, holding all else constant. This effect is
statistically significant (p \textless{} 0.001).

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{beta1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(model\_level)[}\StringTok{"budget"}\NormalTok{]}
\NormalTok{se1 }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(model\_level)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"budget"}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{]}
\NormalTok{df\_resid }\OtherTok{\textless{}{-}}\NormalTok{ model\_level}\SpecialCharTok{$}\NormalTok{df.residual}

\NormalTok{t\_stat }\OtherTok{\textless{}{-}}\NormalTok{ (beta1 }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ se1}
\NormalTok{t\_stat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   budget 
## 19.56605
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p\_value }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pt}\NormalTok{(t\_stat, }\AttributeTok{df =}\NormalTok{ df\_resid)}
\NormalTok{p\_value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## budget 
##      0
\end{verbatim}

Null hypothesis (\(H_0\)): \(\beta_1 \leq 1\). Alternative hypothesis
(\(H_1\)): \(\beta_1 > 1\). Significance level: \(\alpha = 0.05\).

The test statistic is \(t = \frac{3.547 - 1}{0.130} \approx 19.57\),
with a corresponding (one-sided) p-value that is essentially 0 (far
below 0.001). Since the p-value is much smaller than \(\alpha = 0.05\),
we reject the null hypothesis. There is strong evidence that
\(\beta_1 > 1\), meaning that a dollar spent on production budget is
associated with more than a dollar increase in revenue, which supports
Chantal's claim.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{revenue))}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{log\_budget  }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{budget }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{, }\FunctionTok{log}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{budget))}

\NormalTok{model\_log }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget, }\AttributeTok{data =}\NormalTok{ movies\_one)}
\FunctionTok{summary}\NormalTok{(model\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log_revenue ~ log_budget, data = movies_one)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.7790  -0.5049   0.2156   0.7958   4.9779 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   1.9906     1.0826   1.839   0.0669 .  
## log_budget    0.9207     0.0633  14.545   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.624 on 322 degrees of freedom
##   (181 observations deleted due to missingness)
## Multiple R-squared:  0.3965, Adjusted R-squared:  0.3946 
## F-statistic: 211.6 on 1 and 322 DF,  p-value: < 2.2e-16
\end{verbatim}

The estimated log-log regression model is
\(\widehat{\text{Log Revenue}}_i = 1.991 + 0.921 \times \text{Log Budget}_i\),
estimated on 324 movies (after dropping movies with a revenue or budget
of zero).

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{coef}\NormalTok{(model\_log)[}\StringTok{"log\_budget"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## log_budget 
##  0.9207402
\end{verbatim}

The estimated value of \(\beta_1\) is approximately 0.921. \(\beta_1\)
can be interpreted as an elasticity: a 1\% increase in production budget
is associated with an approximately 0.92\% increase in revenue, on
average. This coefficient is statistically significant (p \textless{}
0.001).

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{summary}\NormalTok{(model\_level)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5961367
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model\_log)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3965097
\end{verbatim}

The level-level model has an \(R^2\) of approximately 0.596, while the
log-log model has an \(R^2\) of approximately 0.397. Based on \(R^2\)
alone, the level-level model appears to fit better. However, this
comparison is not entirely fair: the two models are estimated on
different numbers of observations (505 for the level-level model vs.~324
for the log-log model, since movies with zero revenue or budget are
dropped in the log-log model), and the dependent variables are on
different scales (dollars vs.~log-dollars), so their \(R^2\) values are
not directly comparable in a strict sense. Looking at the diagnostics,
the level-level model also shows extremely high skewness and kurtosis in
its residuals (skew ≈ 6.99, kurtosis ≈ 103), suggesting its errors are
far from normally distributed and likely driven by a few extreme
outliers (like Avatar). The log-log model's residuals are much closer to
a well-behaved distribution, even though its raw \(R^2\) is lower. This
suggests the log-log model may actually provide a more reliable fit,
even though it explains less variance on the original scale.

\emph{step g}

Based on the regression results, Chantal appears to be correct: in both
the level-level and log-log models, the relationship between budget and
revenue is positive and statistically significant, and the hypothesis
test in c.~confirms that each dollar of budget is associated with more
than a dollar of additional revenue (\(\beta_1 \approx 3.55 > 1\)). This
suggests that, on average, production spending is more than offset by
the resulting increase in revenue.

However, we would advise the studio to be cautious before concluding
that increasing budgets is always a good strategy. This is a
correlational, not necessarily causal, relationship: successful movies
may attract larger budgets in anticipation of success (reverse
causality), and the result is heavily influenced by a small number of
very high-budget blockbusters. We would advise the studio not to simply
conclude ``always spend more'', but to investigate which types of movies
generate the best return per dollar spent, rather than assuming the same
relationship holds equally for every production.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Make a scatterplot with log revenue on the y-axis, and log budget on
  the x-axis. Within the same scatterplot, draw a straight line which
  summarizes the association between the log of revenue and log of
  budget. \textbf{[3 points]}
\item
  Using the insights from the scatterplot, your linear model, and your
  data, find an example of a movie that vastly overperformed. That
  means, find a movie that had much more revenue than expected, given
  its budget. For this movie, report its log of revenue, its predicted
  log of revenue, and its residual. \textbf{[3 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{ggplot}\NormalTok{(movies\_one, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ log\_budget, }\AttributeTok{y =}\NormalTok{ log\_revenue)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Log revenue vs. log budget"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Log of budget"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Log of revenue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 181 rows containing non-finite outside the scale range
## (`stat_smooth()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 181 rows containing missing values or values outside the scale range
## (`geom_point()`).
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-28-1.pdf}}

The scatter plot shows a clear positive association between log budget
and log revenue: movies with higher budgets tend to also have higher
revenue. The fitted straight line, based on the regression model from
question 1d, summarizes this relationship. There is still considerable
scatter around the line, meaning that budget alone does not perfectly
predict revenue.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{predicted\_log\_revenue }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_log, }\AttributeTok{newdata =}\NormalTok{ movies\_one)}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{residual }\OtherTok{\textless{}{-}}\NormalTok{ movies\_one}\SpecialCharTok{$}\NormalTok{log\_revenue }\SpecialCharTok{{-}}\NormalTok{ movies\_one}\SpecialCharTok{$}\NormalTok{predicted\_log\_revenue}

\NormalTok{movies\_one }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(residual)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(title, log\_revenue, predicted\_log\_revenue, residual) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{head}\NormalTok{(}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 4
##   title             log_revenue predicted_log_revenue residual
##   <chr>                   <dbl>                 <dbl>    <dbl>
## 1 The Gallows              17.6                  12.6     4.98
## 2 Saw                      18.5                  14.9     3.58
## 3 Clerks                   15.0                  11.4     3.58
## 4 Primer                   13.0                  10.1     2.82
## 5 The King's Speech        19.8                  17.2     2.64
\end{verbatim}

A movie that vastly overperformed, given its budget, is ``The Gallows''.
Its log of revenue was approximately 17.57, while the model predicted a
log of revenue of approximately 13.33, given its (low) budget of only
100,000 dollars. This gives a residual of approximately 4.24, the
largest positive residual in the data set. In other words, the actual
revenue of \$42.7 million was far higher than what the model would
expect based on its small budget alone, this movie earned much more than
its budget would predict.

\section{Week 5}\label{week-5}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Make a frequency table of the variable genre. Which are the three
  genres that occur the most? \textbf{[2 points]}
\item
  Create a new variable called genre2. Make sure that the three most
  popular genres remain the same, but that all the other genres get
  categorized into one genre called ``Other''. Report a frequency table
  of this new variable genre2. \textbf{[2 points]}
\item
  Estimate an OLS model which has as dependent variable the log of
  revenue of a movie, and as independent variable the log of budget, a
  dummy for each level that genre2 can take, and the year of release.
  Show a summary of the resulting model and interpret each coefficient.
  \textbf{[4 points]}
\end{enumerate}

The movie studio that you work at is releasing a new movie in 2026. It
will be a Drama movie with a budget of 20,000,0000. It will have a
runtime of 120 minutes.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Estimate a model that is able to predict the revenue of this movie.
  Give its predicted revenue and include a 90\% prediction interval.
  \textbf{[5 points]}
\item
  Plot the residuals against various independent variables in the model.
  Do you find any evidence of heteroskedasticity? \textbf{[2 points]}
\item
  One executive at the studio wants to time the release of the movie to
  a specific month of the year such that they can maximize revenue.
  Another executive is of the opinion that the month in which the movie
  is released will not have a big impact on its revenue. Estimate a
  model that can test whether the month of release impacts the revenue
  of a movie. Use an appropriate hypothesis test to test whether month
  of release matters. What would you advise the movie studio regarding
  the timing of the release of the movie? \textbf{[5 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\FunctionTok{table}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{genre)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      Action   Adventure      Comedy       Crime Documentary       Drama 
##          38           8         104           2          11         244 
##      Family     Fantasy     Fiction      Horror       Music     Romance 
##          10           2           6           8           1           1 
##    Thriller 
##          65
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sort}\NormalTok{(}\FunctionTok{table}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{genre), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##       Drama      Comedy    Thriller      Action Documentary      Family 
##         244         104          65          38          11          10 
##   Adventure      Horror     Fiction       Crime     Fantasy       Music 
##           8           8           6           2           2           1 
##     Romance 
##           1
\end{verbatim}

The three most common genres are Drama 244 movies, Comedy 104 movies and
Thriller 65 movies.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{genre2 }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{genre }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Drama"}\NormalTok{, }\StringTok{"Comedy"}\NormalTok{, }\StringTok{"Thriller"}\NormalTok{),}
\NormalTok{                             movies\_one}\SpecialCharTok{$}\NormalTok{genre, }\StringTok{"Other"}\NormalTok{)}

\FunctionTok{table}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{genre2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Comedy    Drama    Other Thriller 
##      104      244       92       65
\end{verbatim}

The new variable genre2 keeps Drama, Comedy, and Thriller as separate
categories, while all other genres (Action, Documentary, Family,
Adventure, Horror, Fiction, Fantasy, and any NA genres) are grouped into
``Other''. The frequency table shows: Drama (244), Comedy (104), Other
(92), and Thriller (65).

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{genre2 }\OtherTok{\textless{}{-}} \FunctionTok{relevel}\NormalTok{(}\FunctionTok{factor}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{genre2), }\AttributeTok{ref =} \StringTok{"Other"}\NormalTok{)}

\NormalTok{model\_genre }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+}\NormalTok{ genre2 }\SpecialCharTok{+}\NormalTok{ release\_year, }\AttributeTok{data =}\NormalTok{ movies\_one)}
\FunctionTok{summary}\NormalTok{(model\_genre)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log_revenue ~ log_budget + genre2 + release_year, 
##     data = movies_one)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.5135  -0.5053   0.2392   0.7900   4.7458 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     1.2764455 27.8518730   0.046    0.963    
## log_budget      0.9110155  0.0633968  14.370   <2e-16 ***
## genre2Comedy    0.3678607  0.2813770   1.307    0.192    
## genre2Drama    -0.2810763  0.2498695  -1.125    0.261    
## genre2Thriller  0.1622609  0.3076178   0.527    0.598    
## release_year    0.0004446  0.0138670   0.032    0.974    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.613 on 318 degrees of freedom
##   (181 observations deleted due to missingness)
## Multiple R-squared:  0.4122, Adjusted R-squared:  0.403 
## F-statistic:  44.6 on 5 and 318 DF,  p-value: < 2.2e-16
\end{verbatim}

-Intercept (1.28): the predicted log revenue for an ``Other''-genre
movie, with a log budget and release year of zero, this value has no
direct real-world interpretation on its own. -log\_budget (0.911):
holding genre and release year constant, a 1\% increase in budget is
associated with an approximately 0.91\% increase in revenue (elasticity
interpretation). This effect is highly significant (p \textless{}
0.001). -genre2Drama (−0.281): holding budget and release year constant,
Drama movies are predicted to have about 28\% lower revenue than
``Other'' genre movies, although this difference is not statistically
significant (p = 0.261). -genre2Comedy (0.368): holding budget and
release year constant, Comedy movies are predicted to have about 37\%
higher revenue than ``Other'' genre movies, but this is also not
statistically significant (p = 0.192). -genre2Thriller (0.162): holding
budget and release year constant, Thriller movies are predicted to have
about 16\% higher revenue than ``Other'' genre movies, not statistically
significant (p = 0.598). -release\_year (0.0004): holding budget and
genre constant, each additional year is associated with an essentially
negligible (and statistically insignificant, p = 0.974) change in log
revenue, suggesting no meaningful time trend once budget and genre are
controlled for.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{model\_predict }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+}\NormalTok{ genre2 }\SpecialCharTok{+}\NormalTok{ release\_year }\SpecialCharTok{+}\NormalTok{ runtime, }\AttributeTok{data =}\NormalTok{ movies\_one)}
\FunctionTok{summary}\NormalTok{(model\_predict)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log_revenue ~ log_budget + genre2 + release_year + 
##     runtime, data = movies_one)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -14.2451  -0.4664   0.2219   0.7775   4.6182 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    -3.474499  27.628408  -0.126  0.90000    
## log_budget      0.835383   0.068606  12.177  < 2e-16 ***
## genre2Comedy    0.539170   0.285546   1.888  0.05991 .  
## genre2Drama    -0.370662   0.249540  -1.485  0.13844    
## genre2Thriller  0.207607   0.304996   0.681  0.49657    
## release_year    0.002641   0.013752   0.192  0.84784    
## runtime         0.014696   0.005383   2.730  0.00669 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.596 on 317 degrees of freedom
##   (181 observations deleted due to missingness)
## Multiple R-squared:  0.4257, Adjusted R-squared:  0.4148 
## F-statistic: 39.16 on 6 and 317 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{new\_movie }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{log\_budget =} \FunctionTok{log}\NormalTok{(}\DecValTok{20000000}\NormalTok{),}
  \AttributeTok{genre2 =} \FunctionTok{factor}\NormalTok{(}\StringTok{"Drama"}\NormalTok{, }\AttributeTok{levels =} \FunctionTok{levels}\NormalTok{(movies\_one}\SpecialCharTok{$}\NormalTok{genre2)),}
  \AttributeTok{release\_year =} \DecValTok{2026}\NormalTok{,}
  \AttributeTok{runtime =} \DecValTok{120}
\NormalTok{)}

\NormalTok{pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model\_predict, }\AttributeTok{newdata =}\NormalTok{ new\_movie, }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{, }\AttributeTok{level =} \FloatTok{0.90}\NormalTok{)}
\NormalTok{pred}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 17.31257 14.63197 19.99316
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{exp}\NormalTok{(pred)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit     lwr       upr
## 1 33018130 2262475 481860391
\end{verbatim}

The model predicts a log revenue of approximately 17.31 for this movie,
which corresponds to a predicted revenue of approximately 33.0 million
dollars. The 90\% prediction interval for log revenue translates to a
revenue interval of roughly 2.3 million dollars to 481.9 million
dollars. This is an extremely wide interval, reflecting the large amount
of unexplained variation in movie revenue even after accounting for
budget, genre, release year, and run time. \emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{model\_predict }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+}\NormalTok{ genre2 }\SpecialCharTok{+}\NormalTok{ release\_year }\SpecialCharTok{+}\NormalTok{ runtime, }
                     \AttributeTok{data =}\NormalTok{ movies\_one, }\AttributeTok{na.action =}\NormalTok{ na.exclude)}

\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{residuals }\OtherTok{\textless{}{-}} \FunctionTok{resid}\NormalTok{(model\_predict)}
\NormalTok{movies\_one}\SpecialCharTok{$}\NormalTok{fitted }\OtherTok{\textless{}{-}} \FunctionTok{fitted}\NormalTok{(model\_predict)}

\FunctionTok{ggplot}\NormalTok{(movies\_one, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ log\_budget, }\AttributeTok{y =}\NormalTok{ residuals)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Residuals vs. log budget"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Log budget"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Residuals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-34-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(movies\_one, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ runtime, }\AttributeTok{y =}\NormalTok{ residuals)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Residuals vs. runtime"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Runtime"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Residuals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-34-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(movies\_one, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ fitted, }\AttributeTok{y =}\NormalTok{ residuals)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Residuals vs. fitted values"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Fitted values"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Residuals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment15_files/figure-latex/unnamed-chunk-34-3.pdf}}

The residual plots against log budget, run time, and the fitted values
do not show a strong, obvious funnel-shaped pattern, the spread of
residuals looks relatively similar across the range of each variable.
This suggests that there is not strong evidence of heteroskedasticity in
this log-log specification. This makes sense: one of the main benefits
of using the log transformation for revenue and budget is that it tends
to stabilize the variance compared to using the raw (level) variables,
where we would expect much more clear heteroskedasticity.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\NormalTok{model\_restricted }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+}\NormalTok{ genre2 }\SpecialCharTok{+}\NormalTok{ release\_year, }\AttributeTok{data =}\NormalTok{ movies\_one)}
\NormalTok{model\_full }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(log\_revenue }\SpecialCharTok{\textasciitilde{}}\NormalTok{ log\_budget }\SpecialCharTok{+}\NormalTok{ genre2 }\SpecialCharTok{+}\NormalTok{ release\_year }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(release\_month), }\AttributeTok{data =}\NormalTok{ movies\_one)}

\FunctionTok{anova}\NormalTok{(model\_restricted, model\_full)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: log_revenue ~ log_budget + genre2 + release_year
## Model 2: log_revenue ~ log_budget + genre2 + release_year + factor(release_month)
##   Res.Df    RSS Df Sum of Sq      F Pr(>F)
## 1    318 826.96                           
## 2    307 792.33 11    34.629 1.2198 0.2727
\end{verbatim}

Null hypothesis (\(H_0\)): the coefficients on all the release-month
dummies are jointly equal to zero (month of release has no effect on
revenue, after controlling for budget, genre, and release year).
Alternative hypothesis (\(H_1\)): at least one release-month dummy
coefficient is different from zero. Significance level:
\(\alpha = 0.05\).

Using an F-test comparing the restricted model (without month) to the
full model (with month dummies), the F-statistic is approximately 1.22,
with a corresponding p-value of approximately 0.27. Since the p-value is
much greater than \(\alpha = 0.05\), we fail to reject the null
hypothesis. There is no statistically significant evidence that the
month of release affects movie revenue, once budget, genre, and release
year are accounted for.

Advice to the studio: based on this analysis, we would advise the studio
that the timing of the release within the year does not appear to have a
statistically significant impact on revenue. Rather than focusing on
choosing a specific ``optimal'' release month, the studio would likely
get more value from focusing on factors that do significantly predict
revenue, such as production budget. That said, this result is purely
statistical and based on a relatively small and selective sample; the
studio may still want to consider other practical factors (such as
competition from other major releases, or qualifying windows for awards
season) when timing a release.

\end{document}
